apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-project
        image: gcr.io/gcp-devops-project-387716/gcpdevops:latest
        ports:
        - containerport: 5000
        env:
          - name: PORT
            value: "5000"